version: '3.9'

services:
  app:
    container_name: pizza_delivery_api
    build: .
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - ${API_PORT}:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: postgres:12
    ports:
      - 5432:5432
    container_name: 'pizza_db'
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: pgadmin12
